Team-Esquizos/EsquizosP2

frontend-xquizos/src/views/VistaAdministrador.vue
Añadi el recuadro con los botones para que se implementen las funcionalidades del administrador
=> Se completo la interfaz de administrador

frontend-xquizos/src/components/modulos.vue
Se agrego funcionalidad para que al apretar el modulo dirija a la vista con la tabla de alumnos
=> SCRUM-7, SCRUM-11 Agregado funcionalidad link

Backend-xquizos/route/routes.js, Backend-xquizos/src/models/curso.js, Backend-xquizos/src/models/datos.js, Backend-xquizos/src/teaching/teachingController.js, Backend-xquizos/src/teaching/teachingModel.js, Backend-xquizos/src/teaching/teachingServices.js, frontend-xquizos/src/components/AppNavbar.vue, frontend-xquizos/src/components/Login.vue, frontend-xquizos/src/mixins/AutenticadorSesion.js, frontend-xquizos/src/router/index.js, frontend-xquizos/src/views/GestorAlumnos.vue, frontend-xquizos/src/views/GestorDatos.vue, frontend-xquizos/src/views/GestorDocentes.vue, frontend-xquizos/src/views/VistaAdministrador.vue, frontend-xquizos/src/views/VistaDocente.vue
Ahora se pueden Añadir, Editar y Eliminar docentes en su respectivo gestor, lo cual se ve reflejado en la base de datos. 
Arreglos varios: Se restringe el acceso desde la ruta directa, se arregla Botón Inicio y Salir.
=> SCRUM-10: Se agrega gestor de docentes

frontend-xquizos/src/views/GestorDatos.vue, frontend-xquizos/src/views/VistaAdministrador.vue
Cambie de lugar el gestor de Datos para que se viera en la vista del administrador, tuve que hacer modificaciones a los archivos de VistaAdministrador y GestorDatos para poder ajustarlo correctamente
=> SCRUM-16 Modificación de vista de administrador

Backend-xquizos/route/routes.js, Backend-xquizos/src/course/courseServices.js, Backend-xquizos/src/student/studentController.js, Backend-xquizos/src/student/studentServices.js, Backend-xquizos/src/teaching/teachingServices.js, frontend-xquizos/src/components/AppNavbarAdm.vue, frontend-xquizos/src/components/modulos.vue, frontend-xquizos/src/router/index.js, frontend-xquizos/src/views/GestorAlumnos.vue, frontend-xquizos/src/views/VistaAdministrador.vue, frontend-xquizos/src/views/VistaAlumnos.vue, frontend-xquizos/src/views/VistaDocente.vue
Se creo la vistaAlumnos donde se muestran todos los alumnos de un modulo con su respectivo titulo y seccion, se modificó el dropdown del perfil para que aparezca el nombre ahí, además de modificar algunas partes del mismo, ahora cierra sesión el dropdown, en la parte izquierda de la navbar dice si es docente o administrador y las funciones aparecen dependiendo si es admin o docente, además se quitó la animación de las tarjetas de los módulos y se trató de mejor el diseño las mismas, al meterse como docente ya se pueden ver los cursos, se ven todos los cursos, ahora en la navbar aparece que es un docente
=> SCRUM-19 Creacion vistaAlumnos

Backend-xquizos/route/routes.js, Backend-xquizos/src/course/courseServices.js, Backend-xquizos/src/courseInstance/courseInstanceController.js, Backend-xquizos/src/courseInstance/courseInstanceServices.js, Backend-xquizos/src/teaching/teachingServices.js, frontend-xquizos/src/views/GestorDocentes.vue
Se implementa la funcionalidad en backend para agregar un docente a cargo de una instancia de curso, además de insertar alumnos de manera manual al sistema (se inserta 1). Estos se agregan a la instancia correspondiente con el código del curso.
=> SCRUM-23: Agregar un docente y Alumno a instancia de curso

Backend-xquizos/route/routes.js, Backend-xquizos/src/comment/commentController.js, Backend-xquizos/src/comment/commentModel.js, Backend-xquizos/src/comment/commentServices.js, Backend-xquizos/src/teaching/teachingServices.js, Backend-xquizos/src/user/userModel.js
Se crea el Schema Comment, que guarda la matricula del estudiante, el rut del docente que lo realizó, el comentario en sí y un peso(que puede cambiar en base a los requerimientos). Además, se implementan las funciones (solo en backend), para agregar comentarios, eliminarlo a partir del Object_ID y obtener todos los comentarios de un estudiante en particular según su matrícula.
***Las rutas para llamarlo desde el front están agregadas en routes.js
=> [SCRUM-27, SCRUM-10]: Comentarios, agregar, eliminar y obtener datos

frontend-xquizos/src/router/index.js, frontend-xquizos/src/views/GestorAlumnos.vue, frontend-xquizos/src/views/GestorCursos.vue, frontend-xquizos/src/views/GestorDocentes.vue, frontend-xquizos/src/views/PerfilAlumno.vue
añadí un perfil para los comentarios de los alumnos, los datos se reciben desde gestor de alumno(por ahora), y se guardan los comentarios en la base de datos.
=> SCRUM-22 SCRUM-27 TODAS MIS TAREITAS(CREO)

Backend-xquizos/route/routes.js, Backend-xquizos/src/courseInstance/courseInstanceController.js, Backend-xquizos/src/courseInstance/courseInstanceServices.js, frontend-xquizos/src/components/Flag.vue, frontend-xquizos/src/router/index.js, frontend-xquizos/src/views/VistaAlumnos.vue, frontend-xquizos/src/views/temp.vue
Ya se hizo el formulario para agregar un comentario al alumno, falta conectar con la bd y se arreglo la obtención de alumnos para la vistaAlumno
=> SCRUM-25 Añadir comentario

frontend-xquizos/src/router/index.js, frontend-xquizos/src/views/CursoPeriodo.vue, frontend-xquizos/src/views/GestorCursosPeriodo.vue
Se muestra una pestaña con los datos del curso, además del nombre completo del docente, este último puede modificarse, siendo cambiado por algunos de los otros docentes presentes en la base de datos.
Además, se muestra la lista de alumnos matriculados en dicho curso, siendo posible ver su perfil. Falta implementar la incorporación de alumnos al curso tanto de manera manual como por csv dentro de la pestaña del curso.
=> SCRUM-34: Se agrega la vista del CursoPeriodo

Backend-xquizos/src/courseInstance/courseInstanceController.js, Backend-xquizos/src/courseInstance/courseInstanceServices.js, frontend-xquizos/src/views/CursoPeriodo.vue
Arreglo de errores varios, como función para mostrar cursos del docente.
En CursoPeriodo se arregló el botón para cambiar el docente de curso.
=> SCRUM-34: Arreglo de errores

frontend-xquizos/src/views/GestorAlumnos.vue, frontend-xquizos/src/views/GestorCursos.vue, frontend-xquizos/src/views/GestorCursosPeriodo.vue, frontend-xquizos/src/views/GestorDocentes.vue
Se agrego una paginación a los gestores para que muestre una cierta cantidad de cursos, alumnos, docentes, etc y la pagina no quede tan grande
=> SCRUM-32 Cambio a los gestores

frontend-xquizos/package-lock.json, frontend-xquizos/package.json, frontend-xquizos/src/views/CursoPeriodo.vue, frontend-xquizos/src/views/GestorAlumnos.vue, frontend-xquizos/src/views/GestorCursos.vue, frontend-xquizos/src/views/GestorDocentes.vue, frontend-xquizos/src/views/VistaAlumnos.vue
se generan archivos excel para exportar los datos de alumnos, profesores, cursos y alumnos inscrito en curso
=> SCRUM-45 generado de archivos excel para exportar la información

frontend-xquizos/src/router/index.js, frontend-xquizos/src/views/PerfilAlumno.vue, frontend-xquizos/src/views/VistaEstadisticas.vue
Ahora es posible ver las estadisticas de los alumnos de forma automatica, agregué codigo a profile y elimine y mejore cosas en vista estadisticas
=> SCRUM-40 realicé mejoras en Estadísticas

Backend-xquizos/route/routes.js, Backend-xquizos/src/comment/commentController.js, Backend-xquizos/src/comment/commentModel.js, Backend-xquizos/src/comment/commentServices.js, Backend-xquizos/src/course/courseServices.js, frontend-xquizos/src/router/index.js, frontend-xquizos/src/views/PerfilAlumno.vue
Se modifica la API que maneja los comentarios, siendo posible agregar nuevos comentarios necesitando el codigo del curso y el periodo, además, se pueden obtener comentarios del alumno en un curso específico(vista docente), o todos los comentarios del alumno de manera global(vista admin). También se implementa obtener todos los comentarios pertenecientes a un curso en un periodo específico.
=> SCRUM-38,SCRUM-39,SCRUM-40: APIs para obtener comentarios con nueva estructura

Backend-xquizos/src/learning/learningController.js, Backend-xquizos/src/learning/learningModel.js, Backend-xquizos/src/learning/learningServices.js, Backend-xquizos/src/learningCourse/courseLearningController.js, Backend-xquizos/src/learningCourse/courseLearningModel.js, Backend-xquizos/src/learningCourse/courseLearningServices.js
Se modifico la vista docente para que se pueda seleccionar el año de los cursos asignados, por defecto es el año actual. Se modifico el backend de igual manera para hacer posible esta funcionalidad. FINALIZADO
=> SCRUM-44: Los cursos en vista docente se eligen por año con un dropdown

frontend-xquizos/src/views/PerfilAlumno.vue, frontend-xquizos/src/views/VistaCurso.vue
Creacion de vista de curso, donde se ven los datos basicos y se implementaran las funcionalidades para ver los aprendizajes del curso, agregar o eliminar estos mismos.
=> SCRUM-35: Se crea la vista de curso para obtener aprendizajes

Backend-xquizos/src/comment/commentServices.js, frontend-xquizos/src/router/index.js, frontend-xquizos/src/views/PerfilAlumno.vue, frontend-xquizos/src/views/VistaAlumnos.vue, frontend-xquizos/src/views/VistaEstadisticas.vue
Se puede ver las estadisticas por periodo en los docente y el admin puede verlas de forma general, ademas arregle alguno errores que habian en otras secciones
=> SCRUM-38 SCRUM-40 Es posible ver las estadisticas en docentes y admin

frontend-xquizos/src/router/index.js, frontend-xquizos/src/views/VistaAlumnos.vue, frontend-xquizos/src/views/VistaEstadisticasGeneralDocente.vue
implemente otra vista para las estadisticas generales, ahora es posible visualizar las estadisticas de todos los alumnos de un modulo
=> SCRUM-39 Vista general de estadistica para los docentes

frontend-xquizos/src/components/Flag.vue, frontend-xquizos/src/components/Profile.vue, frontend-xquizos/src/components/ResumenAlum.vue, frontend-xquizos/src/components/Slide.vue, frontend-xquizos/src/views/CursoPeriodo.vue, frontend-xquizos/src/views/PerfilAlumno.vue, frontend-xquizos/src/views/VistaAlumnos.vue, frontend-xquizos/src/views/VistaEstadisticas.vue, frontend-xquizos/src/views/temp.vue
Se cambio completamente el perfilAlumno (botones, estructura, margenes, etc), se cambio también una parte de estadísticas pedida por pablito
=> SCRUM-46 Muchos cambios a la perfilAumno

frontend-xquizos/src/views/VistaAlumnos.vue, frontend-xquizos/src/views/VistaEstadisticasGeneralDocente.vue
Se arreglo pequeño error con la vistaAlumno y cambio de fondo a estadisticas
=> SCRUM-46 Cambios pequeños

Backend-xquizos/route/routes.js, Backend-xquizos/src/controllers/ModulosController.js, Backend-xquizos/src/learning/learningModel.js, Backend-xquizos/src/learningCourse/courseLearningModel.js, Backend-xquizos/src/learningCourse/courseLearningServices.js, frontend-xquizos/src/views/VistaCurso.vue
Funcionalidades completas en vista curso
=> SCRUM-35: Se implementan ultimas funcionalidades de aprendizajes en VistaCurso

frontend-xquizos/src/components/Slide.vue
Cambio del slide en perfilAlumno
=> SCRUM-46 Cambios
